### ISSUE TITLE
Remove intersitial task events - implement Upsert

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-relay#80]
Different task status are captured as events. 

- the completed event should `replace` the interstitial events so that the only remaining status is the correct end-state for the tasks of (completed vs executor error)
- final task event contains - how long it was queued/running

**Comment by rosibaj** [comment]
@andricDu Are there any deploy events left here?

**Comment by andricDu** [comment]
@rosibaj I was waiting for the elasticsearch sharding changes to be done by @lepsalex so it can all be done at once at reindex.
